---
abstract: 'Session-based logging platform on top of MongoDB'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pye
requires:
  Carp: 0
  Getopt::Compact: 0
  JSON: 0
  MongoDB: 0
  MongoDB::Code: 0
  Term::ANSIColor: 0
  Text::SpanningTable: 0
  Tie::IxHash: 0
  lib: 0
  perl: 5.006
  strict: 0
  version: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/Pye
  repository: https://github.com/ido50/Pye.git
version: 1.000001
